# Generated by Django 5.1.3 on 2025-02-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('pt', 'Portuguese'), ('en', 'English'), ('fr', 'French'), ('it', 'Italian')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('MX', 'Mexico'), ('BR', 'Brazil'), ('US', 'United States of America'), ('FR', 'France'), ('IT', 'Italy')], default='US', max_length=2),
        ),
    ]
