# Generated by Django 5.1.6 on 2025-02-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_user_language_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('MX', 'Mexico'), ('CO', 'Colombia'), ('AR', 'Argentina'), ('PE', 'Peru'), ('BR', 'Brazil'), ('PT', 'Portugal'), ('AU', 'Australia'), ('US', 'United States of America'), ('UK', 'United Kingdom'), ('FR', 'France'), ('IT', 'Italy'), ('CN', 'China'), ('RU', 'Russia'), ('JP', 'Japan'), ('DE', 'Germany')], default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('pt', 'Portuguese'), ('en', 'English'), ('fr', 'French'), ('it', 'Italian'), ('jp', 'Japanese'), ('cn', 'Chinese'), ('ru', 'Russian'), ('ge', 'German')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default_profile_picture.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
