# Generated by Django 5.1.6 on 2025-02-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_user_country_alter_user_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='img/default_profile_picture.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
